gps:
  gps_publisher:
    std_position: 2.5
    std_velocity: 0.05
    publish_frequency: 10

odom:
  odometry_publisher:
    alpha_1: 0.003    # influence of the rotation on the rotation
    alpha_2: 0.002   # influence of the translation on the rotation
    alpha_3: 0.02    # influence of the translation on the translation
    alpha_4: 0.0003    # influence of the rotation on the translation

    frame_id: "odom"
    child_frame_id: "base_footprint"
    publish_frequency: 50.0
    publish_tf_gt: true
    publish_tf_noised: false

center_imu:
  wait_time: 3.5
  averaging_time: 3.0

perception:
  cones_perception:
    std_position: 0.03            # 0.03 for the velodyne
    std_position_linear: 0.0      # 0.0 for the velodyne and the camera
    std_position_quadratic: 0.0   # ? for the camera
    noise_measurement: true
    range: 10.0
    absolute_frame: 'world'  # FIXME: not used anymore
    sensor_frame: 'velodyne'
    publish_frequency: 10.0
    publish_undetected_cones: true
    publish_sensor: false

  cones_detected_visualizer:
    publish_frequency: 10.0
    marker_scale: 0.5
    marker_height: 0.2
    namespace: 'gazebo_cones'

  cones_undetected_visualizer:
    publish_frequency: 10.0
    marker_scale: 0.5
    marker_height: 0.2
    namespace: 'gazebo_cones'
