gps:
  gps_publisher:
    std_position: 10.0
    std_velocity: 1.0
    publish_frequency: 10

odom:
  odometry_publisher:
    alpha_1: 1.1    # influence of the rotation on the rotation
    alpha_2: 0.03   # influence of the translation on the rotation
    alpha_3: 0.4    # influence of the translation on the translation
    alpha_4: 0.4    # influence of the rotation on the translation

    frame_id: "odom"
    child_frame_id: "base_footprint"
    publish_frequency: 50.0
    publish_tf_gt: true
    publish_tf_noised: false

perception:
  cones_perception:
    std_position: 0.03            # 0.03 for the velodyne
    std_position_linear: 0.0      # 0.0 for the velodyne and the camera
    std_position_quadratic: 0.0   # ? for the camera
    range: 10.0
    absolute_frame: 'world'
    sensor_frame: 'velodyne'
    publish_frequency: 10.0
    display_undetected_cones: true

  cones_detected_visualizer:
    publish_frequency: 10.0
    marker_scale: 0.5
    marker_height: 0.2
    namespace: 'gazebo_cones'

  cones_undetected_visualizer:
    publish_frequency: 10.0
    marker_scale: 0.5
    marker_height: 0.2
    namespace: 'gazebo_cones'
